const state = { config: null, proof: null };
const $ = (id) => document.getElementById(id);
const trust = $('trust'); const summary = $('summary'); const prompt = $('prompt'); const send = $('send');
function canonicalModelID(value) { return /^[a-z0-9][a-z0-9._-]{0,127}\/[a-z0-9][a-z0-9._-]{0,127}$/.test(value); }
function setTrust(kind, text) { trust.className = `state ${kind}`; trust.textContent = text; }
function addMessage(role, text) { const item=document.createElement('article'); item.className='message'; const who=document.createElement('b'); who.textContent=role; item.append(who, document.createElement('br'), document.createTextNode(text)); $('messages').append(item); }
async function loadConfig() { const response = await fetch('./config.json', {cache:'no-store'}); if (!response.ok) throw new Error('configuration unavailable'); const config=await response.json(); if (!Array.isArray(config.models) || config.models.some((m)=>!canonicalModelID(m.id))) throw new Error('configuration contains a non-canonical model ID'); state.config=config; $('evidence').href=config.policy_url; for (const model of config.models) { const option=document.createElement('option'); option.value=model.id; option.textContent=model.label || model.id; $('model').append(option); } }
async function verify() { setTrust('pending','Verifying runtime…'); summary.textContent='Fetching fresh evidence and validating it in this browser.'; try { if (typeof window.AdverserialHardwareVerifier !== 'function') throw new Error('No independent browser hardware verifier is installed. Prompts remain disabled.'); const model=$('model').value; const proof=await window.AdverserialHardwareVerifier({attestationUrl:state.config.attestation_url, policyUrl:state.config.policy_url, modelId:model, apiBaseUrl:state.config.api_base_url}); if (!proof || proof.verified !== true || !proof.verifier) throw new Error('The independent verifier did not accept the runtime evidence.'); state.proof=proof; setTrust('verified',`Verified: ${proof.verifier}`); summary.textContent=`Verified ${model}. This browser accepted fresh policy and hardware evidence.`; prompt.disabled=false; send.disabled=false; } catch (error) { state.proof=null; prompt.disabled=true; send.disabled=true; setTrust('failed','Verification failed'); summary.textContent=error instanceof Error ? error.message : 'Verification failed.'; } }
$('verify').addEventListener('click',verify);
$('composer').addEventListener('submit', async (event) => { event.preventDefault(); if (!state.proof) return; const text=prompt.value.trim(); if (!text) return; addMessage('YOU',text); prompt.value=''; send.disabled=true; try { const response=await fetch(`${state.config.api_base_url}/chat/completions`, {method:'POST',headers:{'content-type':'application/json','x-adverserial-proof':state.proof.receipt || ''},body:JSON.stringify({model:$('model').value,messages:[{role:'user',content:text}],stream:false})}); if (!response.ok) throw new Error(`API request failed (${response.status})`); const payload=await response.json(); addMessage('MODEL',payload.choices?.[0]?.message?.content || 'No completion returned.'); } catch(error) { addMessage('SYSTEM',error instanceof Error ? error.message : 'Request failed.'); } finally { send.disabled=false; } });
loadConfig().catch((error)=>{setTrust('failed','Configuration failed');summary.textContent=error instanceof Error?error.message:'Configuration failed.'});
